version: '3'
services:
  postgres:
    image: postgres:alpine3.18
    volumes:
      - /Users/lucas/Documents/Workspace/quarkus/PostgreSQL:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "5050:80"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge